name: 'dap'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'domain_dbt'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
#test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["../../dags/domain_utils/macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

models:
  my_transfer_project:
    staging_coreruby:
      +materialized: view
      +schema: staging
      +enabled: true         # Always enabled in all environments
    
    intermediate:
      +materialized: table
      +schema: intermediate
      +enabled: true         # Always enabled in all environments
      payments:
        +schema: int_payments
      services:
        +schema: int_services
    
    marts:
      +materialized: table
      +schema: marts
      finance:
        +schema: finance_mart
        +enabled: "{{ target.name in ['prod', 'preprod'] }}"  # Only in prod/preprod