# models/staging_coreruby/coreruby/schema.yml
version: 2

models:
  - name: stg_coreruby_transactions
    description: "Cleaned transactions data"
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: price_cents
        tests:
          - not_null

  - name: stg_coreruby_credit_cards
    description: "Cleaned credit card data"
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: masked_number
        tests:
          - not_null

  - name: stg_coreruby_transaction_details
    description: "Tax-related transaction details"
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: name
        tests:
          - not_null
          - accepted_values:
              values: ['GST', 'HST', 'PST']
              
  - name: stg_coreruby_consultants
    description: "Cleaned consultants data"
    columns:
      - name: id
        tests:
          - unique
          - not_null

  - name: stg_coreruby_consultants_regions
    description: "Consultant region mappings"
    columns:
      - name: consultant_id
        tests:
          - not_null
      - name: region_id
        tests:
          - not_null

  - name: stg_coreruby_specialisms
    description: "Consultant specialisms"
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: specialism_name
        tests:
          - not_null

  - name: stg_coreruby_specialism_categories
    description: "Specialism categories"
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: category_name
        tests:
          - not_null

  - name: stg_coreruby_appointment_service_type
    description: "Appointment service type"
    columns:
      - name: uuid
        tests:
          - unique
          - not_null
      - name: name
        tests:
          - not_null